# Generated by Django 2.2.4 on 2019-09-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('title', models.CharField(max_length=512)),
                ('publisher', models.CharField(max_length=512)),
                ('language', models.CharField(max_length=64)),
                ('date', models.DateTimeField()),
                ('creator', models.CharField(max_length=512)),
                ('isbn', models.CharField(max_length=32)),
                ('iclass', models.CharField(max_length=64)),
                ('asin', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
    ]
