# Generated by Django 2.2.4 on 2019-09-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='date',
        ),
    ]
