# Generated by Django 2.2.4 on 2020-10-06 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('kindle', '0002_remove_ebook_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('price', models.CharField(max_length=64)),
                ('num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
