# Generated by Django 2.2.4 on 2020-10-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindle', '0003_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='num',
            new_name='user',
        ),
    ]
