# Generated by Django 2.2.4 on 2020-10-09 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kindle', '0006_star_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebookreal',
            fields=[
                ('md5', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=1024)),
                ('size', models.IntegerField()),
                ('ebook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindle.Ebook')),
            ],
        ),
    ]
