# Generated by Django 2.2.4 on 2020-10-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindle', '0009_auto_20201010_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebookreal',
            name='ebook',
        ),
        migrations.AddField(
            model_name='ebookreal',
            name='asin',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
