# Generated by Django 2.2.4 on 2020-10-17 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kindle', '0013_auto_20201017_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebookreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('edittime', models.DateTimeField(null=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindle.Ebook')),
                ('ebookreviews', models.ManyToManyField(related_name='_ebookreview_ebookreviews_+', to='kindle.Ebookreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
