# Generated by Django 2.2.4 on 2020-10-17 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindle', '0014_ebookreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebookreview',
            name='ebook',
        ),
        migrations.RemoveField(
            model_name='ebookreview',
            name='ebookreviews',
        ),
        migrations.RemoveField(
            model_name='ebookreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Ebookreview',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
