# Generated by Django 2.2.4 on 2020-10-17 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindle', '0016_ebookreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ebookreview',
        ),
    ]
