# Generated by Django 2.2.4 on 2020-10-17 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindle', '0019_auto_20201017_0631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ebookreview',
        ),
    ]
